#!/bin/bash

CUR=/proc/stat
USER=$(whoami)
PRE=/tmp/${USER}-prestat

if [ ! -f $PRE ]; then
  head -1 $CUR > $PRE
  exit 1
fi

awk '
  /cpu /{
	if (match(FILENAME,"prestat")) {
		pretotal = $2+$3+$4+$5; preidle = $5;
	} else {
		ctotal = $2+$3+$4+$5; cidle = $5;
	}
  }
  END {
	dtotal = ctotal - pretotal
	didle = cidle - preidle
	printf("%d%c",(((dtotal - didle) * 100) / dtotal),37)
  }
' $PRE $CUR

head -1 $CUR > $PRE

