#!/usr/bin/bash

if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
  os=$(/usr/bin/lsb_release -i -s)
  ver=$(/usr/bin/lsb_release -r -s)
  echo $os $ver
elif [ -f /etc/centos-release ]; then
  ver=$(cat /etc/centos-release | awk 'match ($0,/[0-9\.]+/) {print substr($0,RSTART,RLENGTH)}')
  echo "CentOS $ver"
elif [ -f /etc/redhat-release ]; then
  ver=$(cat /etc/redhat-release | awk 'match ($0,/[0-9\.]+/) {print substr($0,RSTART,RLENGTH)}')
  echo "Red Hat $ver"
elif [ -f /etc/rpi-issue ]; then
  ver=$(head -1 /etc/rpi-issue | awk '{print $4}')
  echo "Raspbian $ver"
elif [ -f /etc/debian_version ]; then
  ver=$(head -1 /etc/debian_version)
  echo "Debian $ver"
elif [ -f /etc/arch-release ]; then
  ver=$(uname -r)
  echo "$ver"
fi

