#!/usr/bin/bash

if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
  ver=$(/usr/bin/lsb_release -d -s | sed s/\"//g )
  echo $ver
elif [ -f /etc/centos-release ]; then
  ver=$(head -1 /etc/centos-release | awk '{print $(NF-1)}')
  echo "CentOS $ver"
elif [ -f /etc/redhat-release ]; then
  ver=$(head -1 /etc/redhat-release | awk '{print $(NF-1)}')
  echo "Red Hat $ver"
elif [ -f /etc/rpi-issue ]; then
  ver=$(head -1 /etc/rpi-issue | awk '{print $4}')
  echo "Raspbian $ver"
elif [ -f /etc/debian_version ]; then
  ver=$(head -1 /etc/debian_version)
  echo "Debian $ver"
elif [ -f /etc/arch-release ]; then
  ver=$(uname -r)
  echo "$ver"
fi

